CREATE ROLE R_ADMIN_SEGURIDAD; 
GRANT CREATE SESSION, CREATE USER TO R_ADMIN_SEGURIDAD; 
GRANT SELECT ON BIENESTAR.ESTUDIANTES TO R_ADMIN_SEGURIDAD; 
--GRANT SELECT ON ALL_USERS TO R_ADMIN_SEGURIDAD; 
GRANT GRANT ANY ROLE TO R_ADMIN_SEGURIDAD;
GRANT GRANT ANY PRIVILEGE TO R_ADMIN_SEGURIDAD;

CREATE ROLE R_ESTUDIANTE;
GRANT CREATE SESION TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.ESTUDIANTES TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.SOLICITUDES TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.CONVOCATORIA TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.SOLICITUDES_APROBADAS TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.TICKET TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.TIQUETERA TO R_ESTUDIANTE;
GRANT UPDATE(ESTADO) ON BIENESTAR.SOLICITUDES_APROBADAS TO R_ESTUDIANTE;

