-- Crear el rol R_ESTUDIANTE
CREATE ROLE R_ESTUDIANTE;

GRANT CREATE SESSION TO R_ESTUDIANTE;

-- Otorgar permisos para consultar tablas
GRANT SELECT ON BIENESTAR.ESTUDIANTE TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.SOLICITUD TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.CONVOCATORIA TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.CONVOCATORIA_TIPO TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.TIPO TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.CONDICION TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.SOLICITUD_APROBADA TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.TIPO_SUBSIDIO TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.TIQUETERA TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.TICKET TO R_ESTUDIANTE;

GRANT INSERT ON BIENESTAR.DOCUMENTO TO R_ESTUDIANTE;
GRANT INSERT ON BIENESTAR.SOLICITUD TO R_ESTUDIANTE;

GRANT UPDATE (ESTADO) ON BIENESTAR.SOLICITUD_APROBADA TO R_ESTUDIANTE;

-- Crear el rol R_ADMIN_PARAMETROS
CREATE ROLE R_ADMIN_PARAMETROS;

GRANT CREATE SESSION TO R_ADMIN_PARAMETROS;

-- Otorgar permisos para insertar, seleccionar y eliminar en la tabla Tipo y Condiciones
GRANT INSERT, SELECT, DELETE ON BIENESTAR.TIPO TO R_ADMIN_PARAMETROS;
GRANT INSERT, SELECT, DELETE ON BIENESTAR.CONVOCATORIA TO R_ADMIN_PARAMETROS;

-- Otorgar permisos para insertar, seleccionar y actualizar en la tabla Tipo Subsidio
GRANT INSERT, SELECT, UPDATE ON BIENESTAR.TIPO_SUBSIDIO TO R_ADMIN_PARAMETROS;

-- Crear el rol R_ADMIN_SEGURIDAD
CREATE ROLE R_ADMIN_SEGURIDAD;

GRANT CREATE SESSION TO R_ADMIN_SEGURIDAD;

-- Otorgar permisos para crear usuarios
GRANT CREATE USER TO R_ADMIN_SEGURIDAD;

-- Otorgar permiso para conceder el rol R_ESTUDIANTE a usuarios de estudiantes

-- Otorgar permisos de consulta y actualización en la tabla Estudiantes
GRANT SELECT ON BIENESTAR.ESTUDIANTE TO R_ADMIN_SEGURIDAD;
GRANT UPDATE(USUARIO) ON BIENESTAR.ESTUDIANTE TO R_ADMIN_SEGURIDAD;

-- Crear el rol R_AUDITOR
CREATE ROLE R_AUDITOR;

GRANT CREATE SESSION TO R_AUDITOR;

-- Otorgar permiso de consulta en todas las tablas de la base de datos
GRANT SELECT ANY TABLE TO R_AUDITOR;


-- Crear el rol R_ADMIN_CONVOCATORIA
CREATE ROLE R_ADMIN_CONVOCATORIA;

GRANT CREATE SESSION TO R_ADMIN_CONVOCATORIA;

-- Otorgar permisos de inserción, consulta y actualización sobre la tabla de Convocatorias
GRANT INSERT, SELECT, UPDATE ON BIENESTAR.CONVOCATORIA TO R_ADMIN_CONVOCATORIA;


-- Crear el rol R_ADMIN_VERIFICACION
CREATE ROLE R_ADMIN_VERIFICACION;

GRANT CREATE SESSION TO R_ADMIN_VERIFICACION;

-- Otorgar permisos de consulta sobre la tabla Convocatoria
GRANT SELECT ON BIENESTAR.CONVOCATORIA TO R_ADMIN_VERIFICACION;

-- Otorgar permisos de consulta y actualización sobre la tabla Solicitudes
GRANT SELECT ON BIENESTAR.SOLICITUD TO R_ADMIN_VERIFICACION;
GRANT UPDATE (ESTADO, MOTIVO_RECHAZO) ON BIENESTAR.SOLICITUD TO R_ADMIN_VERIFICACION;
-- Otorgar permisos de consulta y actualización sobre la tabla Documentos
GRANT SELECT ON BIENESTAR.DOCUMENTO TO R_ADMIN_VERIFICACION;
GRANT UPDATE (ESTADO) ON BIENESTAR.DOCUMENTO TO R_ADMIN_VERIFICACION;

GRANT EXECUTE ON bienestar.PK_CALCULAR_PUNTAJE TO R_ADMIN_VERIFICACION;
GRANT EXECUTE ON bienestar.PK_ASIGNAR_BENEFICIO TO R_ADMIN_VERIFICACION;
GRANT EXECUTE ON bienestar.PK_PUBLICACION TO R_ADMIN_VERIFICACION;


-- Crear el rol R_ADMIN_SUPERVISOR
CREATE ROLE R_ADMIN_SUPERVISOR;

GRANT CREATE SESSION TO R_ADMIN_SUPERVISOR;

-- Otorgar permisos de inserción y lectura (reemplazando "read" por "select") sobre la tabla Actividades
GRANT INSERT, SELECT ON BIENESTAR.ACTIVIDAD_DE_APOYO TO R_ADMIN_SUPERVISOR;

GRANT INSERT ON BIENESTAR.SOLICITUD_APROBADA_ACTIVIDAD_DE_APOYO TO R_ADMIN_SUPERVISOR;

-- Otorgar permisos de consulta y actualización sobre la tabla Solicitudes_Aprobadas
GRANT SELECT, UPDATE (ESTADO, MOTIVO_FINALIZACION) ON BIENESTAR.SOLICITUD_APROBADA TO R_ADMIN_SUPERVISOR;



--Usuario por defecto
--GRANT R_ESTUDIANTE TO R_ADMIN_SEGURIDAD WITH ADMIN OPTION;

--CREATE USER ADM_SEG IDENTIFIED BY ADM_SEG DEFAULT TABLESPACE APOYODEF TEMPORARY TABLESPACE APOYOTEMP1 QUOTA 2M ON APOYODEF;
--GRANT R_ADMIN_SEGURIDAD TO ADM_SEG;