CREATE ROLE R_ADMIN_SEGURIDAD; 
GRANT CREATE SESSION, CREATE USER TO R_ADMIN_SEGURIDAD; 
GRANT SELECT ON BIENESTAR.ESTUDIANTES TO R_ADMIN_SEGURIDAD; 
GRANT UPDATE(USUARIO) ON BIENESTAR.ESTUDIANTES TO R_ADMIN_SEGURIDAD; 
--GRANT SELECT ON ALL_USERS TO R_ADMIN_SEGURIDAD; 
GRANT GRANT ANY ROLE TO R_ADMIN_SEGURIDAD;
GRANT GRANT ANY PRIVILEGE TO R_ADMIN_SEGURIDAD;

CREATE ROLE R_ESTUDIANTE;
GRANT CREATE SESSION TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.ESTUDIANTES TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.SOLICITUDES TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.CONVOCATORIA TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.SOLICITUDES_APROBADAS TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.TICKET TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.TIQUETERA TO R_ESTUDIANTE;
GRANT UPDATE(ESTADO) ON BIENESTAR.SOLICITUDES_APROBADAS TO R_ESTUDIANTE;

GRANT SELECT ON BIENESTAR.CONVOCATORIA_TIPO TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.TIPO TO R_ESTUDIANTE;
GRANT SELECT ON BIENESTAR.CONDICIONES TO R_ESTUDIANTE;
GRANT INSERT ON BIENESTAR.DOCUMENTOS TO R_ESTUDIANTE;
GRANT INSERT ON BIENESTAR.SOLICITUDES TO R_ESTUDIANTE;




CREATE ROLE R_PARAPRUEBAS; 
GRANT SELECT ON BIENESTAR.DOCUMENTOS TO R_PARAPRUEBAS;
GRANT UPDATE(ESTADO) ON BIENESTAR.DOCUMENTOS TO R_PARAPRUEBAS;
GRANT UPDATE(ESTADO) ON BIENESTAR.SOLICITUDES TO R_PARAPRUEBAS;