CREATE USER ADM_SEG IDENTIFIED BY ADM_SEG DEFAULT TABLESPACE BRYDEF TEMPORARY TABLESPACE BRYTMP QUOTA 2M ON BRYDEF PASSWORD EXPIRE;
GRANT R_ADMIN_SEGURIDAD TO ADM_SEG;


CREATE USER U_PEPITO2 IDENTIFIED BY PEPITO2 DEFAULT TABLESPACE BRYDEF TEMPORARY TABLESPACE BRYTMP QUOTA 2M ON BRYDEF;
GRANT R_ADMIN_SEGURIDAD, R_PARAPRUEBAS TO U_PEPITO2;
GRANT R_ADMIN_SEGURIDAD TO U_PEPITO;