
-- Crear el rol R_ADMIN_SEGURIDAD
CREATE ROLE R_ADMIN_SEGURIDAD;

GRANT CREATE SESSION TO R_ADMIN_SEGURIDAD;

-- Otorgar permisos para crear usuarios
GRANT CREATE USER TO R_ADMIN_SEGURIDAD;

-- Otorgar permiso para conceder el rol R_ESTUDIANTE a usuarios de estudiantes

-- Otorgar permisos de consulta y actualización en la tabla Estudiantes
GRANT SELECT ON BIENESTAR.ESTUDIANTE TO R_ADMIN_SEGURIDAD;
GRANT UPDATE(USUARIO) ON BIENESTAR.ESTUDIANTE TO R_ADMIN_SEGURIDAD;

--Antes
--GRANT R_ESTUDIANTE TO R_ADMIN_SEGURIDAD WITH ADMIN OPTION;

-- CREARLO COMO SYSTEM
CREATE OR REPLACE PROCEDURE ASIGNAR_ROL_ESTUDIANTE(p_usuario IN VARCHAR2)
AS
BEGIN
    EXECUTE IMMEDIATE 'GRANT R_ESTUDIANTE TO ' || p_usuario;
END;
/

GRANT EXECUTE ON SYSTEM.ASIGNAR_ROL_ESTUDIANTE TO R_ADMIN_SEGURIDAD;

CREATE USER ADM_SEG IDENTIFIED BY ADM_SEG DEFAULT TABLESPACE APOYODEF TEMPORARY TABLESPACE APOYOTEMP1 QUOTA 2M ON APOYODEF;
GRANT R_ADMIN_SEGURIDAD TO ADM_SEG;